spring:
  application:
    name: ConnectaComunidade
  datasource:
    url: jdbc:postgresql://localhost:5433/connecta_comunidade_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect