services:
  postgres:
    image: postgres:latest
    container_name: cc_postgres
    environment:
      POSTGRES_DB: connecta_comunidade_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - connecta-comunidade:/var/lib/postgresql/data
    networks:
      - connecta-network

volumes:
  connecta-comunidade:

networks:
  connecta-network:
    driver: bridge